### ISSUE TITLE
Use `warnings.warn` instead of `logging.warn`

### ISSUE THREAD

**Issue by MaxNollet** [Bovi-analytics/DigitalCowSimulationPlatform#18]
# What's wrong?
In [`src/chain_simulator/utilities.py`](https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py), warnings are communicated to the user using [`logging.Logger.warning`](https://docs.python.org/3/library/logging.html#logging.Logger.warning). Based on [Logging HOWTO - When to use logging](https://docs.python.org/3/howto/logging.html#when-to-use-logging), those warnings should be communicated using [`warnings`](https://docs.python.org/3/library/warnings.html). This is because these are cases where the client appication should be modified to rid the warnings.

# Resolution
Function `validate_matrix_sum` should be updated to use [`warnings`](https://docs.python.org/3/library/warnings.html):
https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py#L47

And function `validate_matrix_positive` should be updated too to use [`warnings`](https://docs.python.org/3/library/warnings.html):
https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py#L87

It may be handy to define a custom warning, something like `InvalidTransitionMatrixWarning`?

# Todo
- [x] Update [validate_matrix_sum](https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py#L47) to use [`warnings`](https://docs.python.org/3/library/warnings.html)
- [x] Add warning to documentation in [validate_matrix_sum](https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py#L47)
- [x] Update [validate_matrix_positive](https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py#L87) to use [`warnings`](https://docs.python.org/3/library/warnings.html)
- [x] Add warning to documentation in [validate_matrix_positive](https://github.com/Bovi-analytics/DigitalCowSimulationPlatform/blob/308057b0d9b2df0fe23deadadbbd3baedd2f412a/src/chain_simulator/utilities.py#L87)
